apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: mydbsecrets
          secret:
            secretName: mydbsecrets
        - name: mounteddbconfig
          configMap:
            name: mounteddbconfig
            items:
              - key: config.yaml
                path: config.yaml
      containers:
        - name: myapp
          image: albertoimpl/myapp
          volumeMounts:
            - mountPath: /config
              name: mounteddbconfig
            - mountPath: /secrets
              name: mydbsecrets
          envFrom:
            - configMapRef:
                name: dbconnection
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
